// Generated by CoffeeScript 1.3.1
(function() {
  var FSMAP, geolocate, updateMap;

  FSMAP = {};

  this.FSMAP = FSMAP;

  FSMAP.map = {};

  FSMAP.loadMap = function(map_div_name) {
    var myOptions;
    myOptions = {
      zoom: 12,
      mapTypeId: google.maps.MapTypeId.ROADMAP,
      mapTypeControlOptions: {
        mapTypeIds: [google.maps.MapTypeId.ROADMAP, google.maps.MapTypeId.SATELLITE, google.maps.MapTypeId.HYBRID, google.maps.MapTypeId.TERRAIN, 'OSM']
      }
    };
    FSMAP.map = new google.maps.Map(document.getElementById(map_div_name), myOptions);
    FSMAP.map.mapTypes.set("OSM", new google.maps.ImageMapType({
      getTileUrl: function(coord, zoom) {
        return "http://tile.openstreetmap.org/" + zoom + "/" + coord.x + "/" + coord.y + ".png";
      },
      tileSize: new google.maps.Size(256, 256),
      name: "OpenStreetMap",
      maxZoom: 18
    }));
    return geolocate(FSMAP.map);
  };

  this.search = function(address) {
    var geocoder;
    geocoder = new google.maps.Geocoder;
    geocoder.geocode({
      address: address
    }, function(results, status) {
      var i, result, resultContent, resultId, _i, _len, _ref;
      if (status === google.maps.GeocoderStatus.OK) {
        updateMap(results[0]);
        if (results.length > 1) {
          FSMAP.results = results;
          $('#search-results').show();
          _ref = FSMAP.results;
          for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
            result = _ref[i];
            resultId = "result-" + i;
            resultContent = ("<a href='javascript:void(0);' id='" + resultId + "'>") + result.formatted_address + '</a>';
            resultContent = "<div>" + resultContent + "</div>";
            $('#search-results').append(resultContent);
            $("#" + resultId).click(function() {
              resultId = this.id.replace('result-', '');
              return updateMap(FSMAP.results[resultId]);
            });
          }
          return console.log(FSMAP.results);
        }
      } else {
        return alert("Not found: " + status);
      }
    });
    return location;
  };

  updateMap = function(result) {
    var location, marker;
    location = result.geometry.location;
    FSMAP.map.setCenter(location);
    marker = new google.maps.Marker({
      position: location,
      map: FSMAP.map
    });
    return google.maps.event.addListener(marker, 'click', function() {
      var infoWindow;
      infoWindow = new google.maps.InfoWindow;
      infoWindow.setContent(result.formatted_address);
      return infoWindow.open(FSMAP.map, marker);
    });
  };

  geolocate = function() {
    var handleNoGeolocation, newyork;
    newyork = new google.maps.LatLng(40.69847032728747, -73.9514422416687);
    handleNoGeolocation = function() {
      return FSMAP.map.setCenter(newyork);
    };
    if (navigator.geolocation) {
      return navigator.geolocation.getCurrentPosition((function(position) {
        var initialLocation;
        initialLocation = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);
        return FSMAP.map.setCenter(initialLocation);
      }), function() {
        return handleNoGeolocation();
      });
    } else {
      return handleNoGeolocation();
    }
  };

}).call(this);
